services:
  db:
    image: postgres:17.0
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: casecobra-db
    volumes:
      - casecobra_pgdata:/var/lib/postgresql/data
volumes:
  casecobra_pgdata: